name: ZarinMah Schedule Test

on:
  schedule:
    - cron: "*/5 * * * *"
      timezone: "Asia/Tehran"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduler test
        run: |
          echo "✅ Scheduled workflow is working"
          date
